on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: cabal-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal-project.freeze') }}
          restore-keys: cabal-
      - uses: haskell-actions/setup@v2
      - run: cabal build --only-dependencies
      - run: cabal build
